import { type NextPage } from "next";
import Head from "next/head";
import useHasMounted from "../hooks/hasMounted";
import { api } from "../utils/api";
import Item from "../components/Item";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  const hasMounted = useHasMounted();
  const getNames = api.db.getNames.useQuery();

  return (
    <>
      <Head>
        <title>Шаблоны Notion от Кирилла</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col bg-slate-100">
        <Navbar />
        {hasMounted && getNames.isFetching && (
          <p className="px-4 font-bold text-slate-600">Загрузка...</p>
        )}
        {hasMounted && getNames.isSuccess && (
          <div className="flex flex-wrap">
            {getNames.data?.map((item) => {
              const title = item.title?.rich_text?.[0]?.plain_text ?? "";

              const description =
                item.description?.rich_text?.[0]?.plain_text ?? "";

              const instruction = item.instruction?.url ?? "";

              const toPublish = item.toPublish?.checkbox;

              const link = item.link?.url ?? "";

              const cover: string = item.cover?.url ?? "";

              if (!toPublish) {
                return null;
              }

              return (
                <Item
                  key={Math.random()}
                  cover={cover}
                  description={description}
                  instruction={instruction}
                  link={link}
                  title={title}
                />
              );
            })}
          </div>
        )}
      </main>
      <Footer />
    </>
  );
};

export default Home;
